modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="CC0"

[[mods]]
modId="enderio_machines"
version="${file.jarVersion}"
displayName="Ender IO Machines"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, agnor99"
description="Machines and all the other cool stuff"
displayURL="http://enderio.com/"
logoFile="logo.png"